/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/bmwF22.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

import gsap from 'gsap'

export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function Car(props) {
    const { nodes, materials } = useGLTF('./models/bmwF22.glb')

    // add
    const ref = useRef();
    const tl = useRef();

    const scroll = useScroll();

    useFrame(() => {
        tl.current.seek(scroll.offset * tl.current.duration());
    });

    useLayoutEffect(()=>{
        tl.current = gsap.timeline();

        // VERTICAL ANIMATION 
        tl.current.to(
            ref.current.position, {
                duration: 2,
                y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
            },
            0
        );
        
    }, []);
    return (
        <group {...props} dispose={null} ref={ref}>
        <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.HGK_1.geometry} material={materials.remap__prim_env_2_spec_} />
            <mesh geometry={nodes.HGK_2.geometry} material={materials.BLACK} />
            <mesh geometry={nodes.HGK_3.geometry} material={materials.cabin_ao__spec_} />
            <mesh geometry={nodes.HGK_4.geometry} material={materials.bmw_logo__spec_} />
            <mesh geometry={nodes.HGK_5.geometry} material={materials.parts_d__spec_} />
            <mesh geometry={nodes.HGK_6.geometry} material={materials.mat_plastic_black__spec_} />
            <mesh geometry={nodes.HGK_7.geometry} material={materials.window__spec_} />
            <mesh geometry={nodes.HGK_8.geometry} material={materials.mat_metal_grey__spec_} />
            <mesh geometry={nodes.HGK_9.geometry} material={materials.ALIUM} />
            <mesh geometry={nodes.HGK_10.geometry} material={materials.colors__spec_} />
            <mesh geometry={nodes.HGK_11.geometry} material={materials.enginesymbols__spec_} />
            <mesh geometry={nodes.HGK_12.geometry} material={materials.enginesymbols2__spec_} />
            <mesh geometry={nodes.HGK_13.geometry} material={materials.weld__spec_} />
            <mesh geometry={nodes.HGK_14.geometry} material={materials.ALIUM2} />
            <mesh geometry={nodes.HGK_15.geometry} material={materials.cooler__spec_} />
            <mesh geometry={nodes.HGK_16.geometry} material={materials.rad_prop__spec_} />
            <mesh geometry={nodes.HGK_17.geometry} material={materials.light_d__spec_} />
            <mesh geometry={nodes.HGK_18.geometry} material={materials.cockpit_belt__spec_} />
            <mesh geometry={nodes.HGK_19.geometry} material={materials.bulloni_d__spec_} />
            <mesh geometry={nodes.HGK_20.geometry} material={materials.decals__spec_} />
            <mesh geometry={nodes.HGK_21.geometry} material={materials.mat_rubber_dark__spec_} />
            <mesh geometry={nodes.HGK_22.geometry} material={materials.interior_lod0__spec_} />
            <mesh geometry={nodes.HGK_23.geometry} material={materials.mirror__env_17_spec_} />
            <mesh geometry={nodes.HGK_24.geometry} material={materials.mat_plastic_grey__spec_} />
            <mesh geometry={nodes.HGK_25.geometry} material={materials.WINDOWS} />
            <mesh geometry={nodes.HGK_26.geometry} material={materials.cockpit_belt_door__spec_} />
            <mesh geometry={nodes.HGK_27.geometry} material={materials.TAIL_GLASS} />
            <mesh geometry={nodes.HGK_28.geometry} material={materials.driftinghu__spec_} />
            <mesh geometry={nodes.HGK_29.geometry} material={materials.ad08_sidewall__spec_} />
            <mesh geometry={nodes.HGK_30.geometry} material={materials.advan__spec_} />
            <mesh geometry={nodes.HGK_31.geometry} material={materials.smw_remap__sec_env_4_spec_} />
            <mesh geometry={nodes.HGK_32.geometry} material={materials.discextras__spec_} />
            <mesh geometry={nodes.HGK_33.geometry} material={materials.brake_disc__env_4_spec_} />
            <mesh geometry={nodes.HGK_34.geometry} material={materials.wheelz__env_3_spec_} />
        </group>
        </group>
    )
}

useGLTF.preload('./models/bmwF22.glb')
